// ============================================================
// Lista dei 195 paesi riconosciuti (193 membri ONU + Vaticano + Palestina)
// ISO Alpha-2, nomi in italiano, emoji bandiera
// ============================================================

export interface Country {
  code:  string   // ISO Alpha-2
  name:  string   // Nome in italiano
  flag:  string   // Emoji bandiera
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan',            flag: '🇦🇫' },
  { code: 'AL', name: 'Albania',                flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria',                flag: '🇩🇿' },
  { code: 'AD', name: 'Andorra',                flag: '🇦🇩' },
  { code: 'AO', name: 'Angola',                 flag: '🇦🇴' },
  { code: 'AG', name: 'Antigua e Barbuda',      flag: '🇦🇬' },
  { code: 'AR', name: 'Argentina',              flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia',                flag: '🇦🇲' },
  { code: 'AU', name: 'Australia',              flag: '🇦🇺' },
  { code: 'AT', name: 'Austria',                flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaigian',            flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas',                flag: '🇧🇸' },
  { code: 'BH', name: 'Bahrein',                flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh',             flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados',               flag: '🇧🇧' },
  { code: 'BY', name: 'Bielorussia',            flag: '🇧🇾' },
  { code: 'BE', name: 'Belgio',                 flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize',                 flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin',                  flag: '🇧🇯' },
  { code: 'BT', name: 'Bhutan',                 flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivia',                flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia ed Erzegovina',   flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana',               flag: '🇧🇼' },
  { code: 'BR', name: 'Brasile',                flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei',                 flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria',               flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso',           flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi',                flag: '🇧🇮' },
  { code: 'CV', name: 'Capo Verde',             flag: '🇨🇻' },
  { code: 'KH', name: 'Cambogia',               flag: '🇰🇭' },
  { code: 'CM', name: 'Camerun',                flag: '🇨🇲' },
  { code: 'CA', name: 'Canada',                 flag: '🇨🇦' },
  { code: 'CF', name: 'Rep. Centrafricana',     flag: '🇨🇫' },
  { code: 'TD', name: 'Ciad',                   flag: '🇹🇩' },
  { code: 'CL', name: 'Cile',                   flag: '🇨🇱' },
  { code: 'CN', name: 'Cina',                   flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia',               flag: '🇨🇴' },
  { code: 'KM', name: 'Comore',                 flag: '🇰🇲' },
  { code: 'CG', name: 'Congo',                  flag: '🇨🇬' },
  { code: 'CD', name: 'Rep. Dem. del Congo',    flag: '🇨🇩' },
  { code: 'CR', name: 'Costa Rica',             flag: '🇨🇷' },
  { code: 'CI', name: 'Costa d\'Avorio',        flag: '🇨🇮' },
  { code: 'HR', name: 'Croazia',                flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba',                   flag: '🇨🇺' },
  { code: 'CY', name: 'Cipro',                  flag: '🇨🇾' },
  { code: 'CZ', name: 'Repubblica Ceca',        flag: '🇨🇿' },
  { code: 'DK', name: 'Danimarca',              flag: '🇩🇰' },
  { code: 'DJ', name: 'Gibuti',                 flag: '🇩🇯' },
  { code: 'DM', name: 'Dominica',               flag: '🇩🇲' },
  { code: 'DO', name: 'Rep. Dominicana',        flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador',                flag: '🇪🇨' },
  { code: 'EG', name: 'Egitto',                 flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador',            flag: '🇸🇻' },
  { code: 'GQ', name: 'Guinea Equatoriale',     flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrea',                flag: '🇪🇷' },
  { code: 'EE', name: 'Estonia',                flag: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini',               flag: '🇸🇿' },
  { code: 'ET', name: 'Etiopia',                flag: '🇪🇹' },
  { code: 'FJ', name: 'Figi',                   flag: '🇫🇯' },
  { code: 'FI', name: 'Finlandia',              flag: '🇫🇮' },
  { code: 'FR', name: 'Francia',                flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon',                  flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia',                 flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia',                flag: '🇬🇪' },
  { code: 'DE', name: 'Germania',               flag: '🇩🇪' },
  { code: 'GH', name: 'Ghana',                  flag: '🇬🇭' },
  { code: 'GR', name: 'Grecia',                 flag: '🇬🇷' },
  { code: 'GD', name: 'Grenada',                flag: '🇬🇩' },
  { code: 'GT', name: 'Guatemala',              flag: '🇬🇹' },
  { code: 'GN', name: 'Guinea',                 flag: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau',          flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana',                 flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti',                  flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras',               flag: '🇭🇳' },
  { code: 'HU', name: 'Ungheria',               flag: '🇭🇺' },
  { code: 'IS', name: 'Islanda',                flag: '🇮🇸' },
  { code: 'IN', name: 'India',                  flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia',              flag: '🇮🇩' },
  { code: 'IR', name: 'Iran',                   flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq',                   flag: '🇮🇶' },
  { code: 'IE', name: 'Irlanda',                flag: '🇮🇪' },
  { code: 'IL', name: 'Israele',                flag: '🇮🇱' },
  { code: 'IT', name: 'Italia',                 flag: '🇮🇹' },
  { code: 'JM', name: 'Giamaica',               flag: '🇯🇲' },
  { code: 'JP', name: 'Giappone',               flag: '🇯🇵' },
  { code: 'JO', name: 'Giordania',              flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakistan',             flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya',                  flag: '🇰🇪' },
  { code: 'KI', name: 'Kiribati',               flag: '🇰🇮' },
  { code: 'KP', name: 'Corea del Nord',         flag: '🇰🇵' },
  { code: 'KR', name: 'Corea del Sud',          flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait',                 flag: '🇰🇼' },
  { code: 'KG', name: 'Kirghizistan',           flag: '🇰🇬' },
  { code: 'LA', name: 'Laos',                   flag: '🇱🇦' },
  { code: 'LV', name: 'Lettonia',               flag: '🇱🇻' },
  { code: 'LB', name: 'Libano',                 flag: '🇱🇧' },
  { code: 'LS', name: 'Lesotho',                flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia',                flag: '🇱🇷' },
  { code: 'LY', name: 'Libia',                  flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein',          flag: '🇱🇮' },
  { code: 'LT', name: 'Lituania',               flag: '🇱🇹' },
  { code: 'LU', name: 'Lussemburgo',            flag: '🇱🇺' },
  { code: 'MG', name: 'Madagascar',             flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi',                 flag: '🇲🇼' },
  { code: 'MY', name: 'Malesia',                flag: '🇲🇾' },
  { code: 'MV', name: 'Maldive',                flag: '🇲🇻' },
  { code: 'ML', name: 'Mali',                   flag: '🇲🇱' },
  { code: 'MT', name: 'Malta',                  flag: '🇲🇹' },
  { code: 'MH', name: 'Isole Marshall',         flag: '🇲🇭' },
  { code: 'MR', name: 'Mauritania',             flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius',              flag: '🇲🇺' },
  { code: 'MX', name: 'Messico',                flag: '🇲🇽' },
  { code: 'FM', name: 'Micronesia',             flag: '🇫🇲' },
  { code: 'MD', name: 'Moldavia',               flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco',                 flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia',               flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro',             flag: '🇲🇪' },
  { code: 'MA', name: 'Marocco',                flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambico',              flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar',                flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia',                flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru',                  flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal',                  flag: '🇳🇵' },
  { code: 'NL', name: 'Paesi Bassi',            flag: '🇳🇱' },
  { code: 'NZ', name: 'Nuova Zelanda',          flag: '🇳🇿' },
  { code: 'NI', name: 'Nicaragua',              flag: '🇳🇮' },
  { code: 'NE', name: 'Niger',                  flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria',                flag: '🇳🇬' },
  { code: 'MK', name: 'Macedonia del Nord',     flag: '🇲🇰' },
  { code: 'NO', name: 'Norvegia',               flag: '🇳🇴' },
  { code: 'OM', name: 'Oman',                   flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan',               flag: '🇵🇰' },
  { code: 'PW', name: 'Palau',                  flag: '🇵🇼' },
  { code: 'PS', name: 'Palestina',              flag: '🇵🇸' },
  { code: 'PA', name: 'Panama',                 flag: '🇵🇦' },
  { code: 'PG', name: 'Papua Nuova Guinea',     flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay',               flag: '🇵🇾' },
  { code: 'PE', name: 'Perù',                   flag: '🇵🇪' },
  { code: 'PH', name: 'Filippine',              flag: '🇵🇭' },
  { code: 'PL', name: 'Polonia',                flag: '🇵🇱' },
  { code: 'PT', name: 'Portogallo',             flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar',                  flag: '🇶🇦' },
  { code: 'RO', name: 'Romania',                flag: '🇷🇴' },
  { code: 'RU', name: 'Russia',                 flag: '🇷🇺' },
  { code: 'RW', name: 'Ruanda',                 flag: '🇷🇼' },
  { code: 'KN', name: 'Saint Kitts e Nevis',    flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia',            flag: '🇱🇨' },
  { code: 'VC', name: 'Saint Vincent',          flag: '🇻🇨' },
  { code: 'WS', name: 'Samoa',                  flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino',             flag: '🇸🇲' },
  { code: 'ST', name: 'São Tomé e Príncipe',    flag: '🇸🇹' },
  { code: 'SA', name: 'Arabia Saudita',         flag: '🇸🇦' },
  { code: 'SN', name: 'Senegal',                flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia',                 flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles',             flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone',           flag: '🇸🇱' },
  { code: 'SG', name: 'Singapore',              flag: '🇸🇬' },
  { code: 'SK', name: 'Slovacchia',             flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia',               flag: '🇸🇮' },
  { code: 'SB', name: 'Isole Salomone',         flag: '🇸🇧' },
  { code: 'SO', name: 'Somalia',                flag: '🇸🇴' },
  { code: 'ZA', name: 'Sudafrica',              flag: '🇿🇦' },
  { code: 'SS', name: 'Sudan del Sud',          flag: '🇸🇸' },
  { code: 'ES', name: 'Spagna',                 flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka',              flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan',                  flag: '🇸🇩' },
  { code: 'SR', name: 'Suriname',               flag: '🇸🇷' },
  { code: 'SE', name: 'Svezia',                 flag: '🇸🇪' },
  { code: 'CH', name: 'Svizzera',               flag: '🇨🇭' },
  { code: 'SY', name: 'Siria',                  flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwan',                 flag: '🇹🇼' },
  { code: 'TJ', name: 'Tagikistan',             flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzania',               flag: '🇹🇿' },
  { code: 'TH', name: 'Thailandia',             flag: '🇹🇭' },
  { code: 'TL', name: 'Timor Est',              flag: '🇹🇱' },
  { code: 'TG', name: 'Togo',                   flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga',                  flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad e Tobago',      flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisia',                flag: '🇹🇳' },
  { code: 'TR', name: 'Turchia',                flag: '🇹🇷' },
  { code: 'TM', name: 'Turkmenistan',           flag: '🇹🇲' },
  { code: 'TV', name: 'Tuvalu',                 flag: '🇹🇻' },
  { code: 'UG', name: 'Uganda',                 flag: '🇺🇬' },
  { code: 'UA', name: 'Ucraina',                flag: '🇺🇦' },
  { code: 'AE', name: 'Emirati Arabi Uniti',    flag: '🇦🇪' },
  { code: 'GB', name: 'Regno Unito',            flag: '🇬🇧' },
  { code: 'US', name: 'Stati Uniti',            flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay',                flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan',             flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu',                flag: '🇻🇺' },
  { code: 'VA', name: 'Vaticano',               flag: '🇻🇦' },
  { code: 'VE', name: 'Venezuela',              flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam',                flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen',                  flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia',                 flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe',               flag: '🇿🇼' },
]

/** Numero standard di paesi riconosciuti per il calcolo % */
export const TOTAL_COUNTRIES = 195

/** Lookup O(1) per codice → paese */
export const COUNTRIES_BY_CODE = new Map<string, Country>(
  COUNTRIES.map(c => [c.code, c])
)
